services:
  _defaults:
    autowire:       true
    autoconfigure:  true
    public:         true


##### Austral Event Subscriber
  austral.seo.url_parameter.event_subscriber:
    class:        Austral\SeoBundle\EventSubscriber\UrlParameterSubscriber
    tags:
      - { name: kernel.event_subscriber }

##### Routing #####
  Austral\SeoBundle\Routing\AustralRouting: "@austral.seo.routing"
  austral.seo.routing:
    class:        Austral\SeoBundle\Routing\AustralRouting
    arguments:
      - '@router'
      - "@austral.http.domains.management"
      - "@austral.seo.url_parameter.management"
      - "@austral.http.config"

##### Twig Extension
  Austral\SeoBundle\TwigExtension\RoutingExtension: "@twig.extension.seo"
  twig.extension.seo:
    class:        Austral\SeoBundle\TwigExtension\RoutingExtension
    arguments:
      - '@austral.seo.routing'
    tags:
      - { name: twig.extension }

##### Services #####

  Austral\SeoBundle\Services\UrlParameterManagement:  "@austral.seo.url_parameter.management"
  austral.seo.url_parameter.management:
    class:        Austral\SeoBundle\Services\UrlParameterManagement
    arguments:
      - "@austral.entity.mapping"
      - "@event_dispatcher"
      - "@austral.entity_manager"
      - "@austral.entity_manager.url_parameter"
      - "@austral.http.domains.management"
      - "@austral.seo.url_parameter.migrate"
      - "@austral.tools.debug"

  Austral\SeoBundle\Services\RedirectionManagement: "@austral.seo.redirection.management"
  austral.seo.redirection.management:
    class: Austral\SeoBundle\Services\RedirectionManagement
    arguments: [ "@austral.seo.config", "@austral.entity_manager.redirection"]

  Austral\SeoBundle\Services\UrlParameterMigrate: "@austral.seo.url_parameter.migrate"
  austral.seo.url_parameter.migrate:
    class: Austral\SeoBundle\Services\UrlParameterMigrate
    arguments: [         "@austral.entity.mapping", "@austral.entity_file.compression"]


##### Listener #####

  austral.seo.doctrine.listener:
    class:        Austral\SeoBundle\Listener\DoctrineListener
    arguments:    ["@austral.entity.mapping","@austral.seo.url_parameter.management", "@austral.seo.redirection.management"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  austral.seo.entity_mapping.listener:
    class:        Austral\SeoBundle\Listener\EntityMappingListener
    arguments:
      - "@service_container"
    tags:
      - { name: kernel.event_listener, event: "austral.event.entity.initialise.mapping", method: mapping }

  austral.seo.elastic_search.listener:
    class:          Austral\SeoBundle\Listener\ElasticSearchListener
    arguments:      ["@austral.entity.mapping", "@austral.http.domains.management", "@austral.seo.url_parameter.management", "@austral.seo.routing"]
    tags:
      - { name: kernel.event_listener, event: "austral.elastic_search.select.objects", method: objects }

  austral.seo.entity_manager.listener:
    class:          Austral\SeoBundle\Listener\EntityManagerListener
    arguments:    ["@austral.seo.url_parameter.management"]
    tags:
      - { name: kernel.event_listener, event: "austral.entity_manager.create", method: createDomain }
      - { name: kernel.event_listener, event: "austral.entity_manager.duplicate", method: duplicateUrlParameter, priority: -1024 }
      - { name: kernel.event_listener, event: "austral.entity_manager.update", method: updateUrlParameter }
      - { name: kernel.event_listener, event: "austral.entity_manager.delete", method: deleteUrlParameter }
      - { name: kernel.event_listener, event: "austral.entity_manager.push.after", method: generateUrlParameter }

  austral.seo.query_builder.listener:
    class:        Austral\SeoBundle\Listener\UrlParameterQueryBuilderListener
    arguments:    ["@austral.seo.url_parameter.management", "@austral.http.domains.management"]
    tags:
      - { name: kernel.event_listener, event: "austral.event.entity.query_builder.condition", method: conditionUrlParameterQuery }

##### Entities Manager #####

  ##### Url Parameter Entity Manager
  Austral\SeoBundle\EntityManager\UrlParameterEntityManager:  "@austral.entity_manager.url_parameter"
  austral.entity_manager.url_parameter:
    class:        Austral\SeoBundle\EntityManager\UrlParameterEntityManager
    arguments:    [ "@doctrine.orm.entity_manager",  "@event_dispatcher", "%austral.entity.url_parameter.class%" ]

  ##### Redirection Entity Manager
  Austral\SeoBundle\EntityManager\RedirectionEntityManager: "@austral.entity_manager.redirection"
  austral.entity_manager.redirection:
    class:        Austral\SeoBundle\EntityManager\RedirectionEntityManager
    arguments:    [ "@doctrine.orm.entity_manager",  "@event_dispatcher", "%austral.entity.redirection.class%" ]

##### Parameters #####
  Austral\SeoBundle\Configuration\SeoConfiguration: "@austral.seo.config"
  austral.seo.config:
    class:        Austral\SeoBundle\Configuration\SeoConfiguration
    arguments:    ["%austral_entity_seo%"]

##### Form Type #####
  Austral\SeoBundle\Form\Type\UrlParameterFormType: "@austral.seo.url_parameter_form_type"
  austral.seo.url_parameter_form_type:
    class:        Austral\SeoBundle\Form\Type\UrlParameterFormType
    arguments:    [ "@security.authorization_checker" ]
    tags:
      - { name: form.type , alias: austral_url_parameter_form_type }